#Version of the docker compose syntax
version: "3.9"

#One or more service.
services: 
#App is just the name of the server that is going to run our docker file. 
  app:  
#We want to build the docker file inside of our current directory. . means current directory
    build: 
      context: .
      args:
        - DEV=true
#Maps port 8000 on our local machine to port 8000 inside our Docker container. This is how we access the network when we
#want to connect to our server. 
    ports: 
      - "8000:8000"
#odd way of mapping directories from our system into the docket container. 
    volumes: 
      - .app:/app
#Command used to run the service. 
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"