#This file can have any name. 
#Configuration file for github actions. 
#--- means that this is a yml file. 
---
name: Checks # name is going to appear in github actions 

on: [push] # the trigger, jobs will run when there is a new push. 

#Jobs 
jobs: 
#ID of the job test-lint
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps: 
      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      # - name: Lint
      #   run: docker-compose run --rm app sh -c "flake8"
